import { CreateCompanyDto } from 'src/modules/companies/dto/create-company.dto';
import { CreatePackageTypeDto } from 'src/modules/package-types/dto/create-package-type.dto';
import { CreateShipmentDto } from 'src/modules/shipments/dto/create-shipment.dto';
import { CreateUserDto } from 'src/modules/users/dto/create-user.dto';

export const users: CreateUserDto[] = [
  {
    email: 'hector@invent.com',
    name: 'Hector Granell',
    password: 'password123',
    username: 'hectorgo',
  },
  {
    email: 'juan@invent.com',
    name: 'Juan Pérez',
    password: 'password',
    username: 'juanperez',
  },
  {
    email: 'maria@invent.com',
    name: 'María García',
    password: 'password',
    username: 'mariagarcia',
  },
  {
    email: 'carlos@invent.com',
    name: 'Carlos Rodríguez',
    password: 'password',
    username: 'carlosrodriguez',
  },
  {
    email: 'laura@invent.com',
    name: 'Laura Fernández',
    password: 'password',
    username: 'laurafernandez',
  },
  {
    email: 'pedro@invent.com',
    name: 'Pedro Martínez',
    password: 'password',
    username: 'pedromartinez',
  },
  {
    email: 'ana@invent.com',
    name: 'Ana Sánchez',
    password: 'password',
    username: 'anasanchez',
  },
];

export const companies: any = [
  {
    name: 'INVENT',
    zips: [],
  },
  {
    name: 'Correos',
    zips: [15, 16, 17, 18, 19],
  },
  {
    name: 'Seur',
    zips: [20, 21, 22, 23, 24, 25],
  },
  {
    name: 'DHL',
    zips: [1, 2, 3, 4, 5, 6],
  },
  {
    name: 'FedEx',
    zips: [30, 32, 33],
  },
  {
    name: 'UPS',
    zips: [34, 35, 36],
  },
];

export const packageType: CreatePackageTypeDto[] = [
  {
    description: 'Paquete ultra ligero',
    formula: 'x * 5',
    min: 0,
    max: 0.1,
  },
  {
    description: 'Paquete ligero',
    formula: 'x * 5 + 1',
    min: 0.1,
    max: 0.3,
  },
  {
    description: 'Paquete estándar',
    formula: 'x * 10',
    min: 0.3,
    max: 5,
  },
  {
    description: 'Paquete pesado',
    formula: 'x * 5 + x + 75',
    min: 5,
    max: 10,
  },
  {
    description: 'Gran volumen',
    formula: '(x - 10) * 7.5 + 130 + x',
    min: 10,
    max: null,
  },
];

export const shipments: any[] = [
  {
    id: '1',
    address: 'Secundino Esnaola Kalea, 36, Bajo',
    zip: '20001',
    sender: 'Juan Pérez',
    recipient: 'María López',
    weight: '0.7',
    price: '7',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '2',
    typeId: '3',
  },
  {
    id: '2',
    address:
      'Parque Tecnológico de, Rda. de Narcís Monturiol, 7, piso 2, puerta 15',
    zip: '46980',
    sender: 'Hector Granell',
    recipient: 'Dámaso González',
    weight: '1.2',
    price: '12',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '3',
    typeId: '3',
  },
  {
    id: '3',
    address: 'Ronda del Calvari',
    zip: '46680',
    sender: 'Ana Sánchez',
    recipient: 'Pedro Ruiz',
    weight: '5.5',
    price: '108',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '3',
    typeId: '4',
  },
  {
    id: '4',
    address: 'Calle Principal',
    zip: '41',
    sender: 'Luis Fernández',
    recipient: 'Elena Martínez',
    weight: '4.1',
    price: '41',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '1',
    typeId: '3',
  },
  {
    id: '5',
    address: 'Avenida del Sol',
    zip: '35',
    sender: 'Carlos Rodríguez',
    recipient: 'Laura Pérez',
    weight: '2.7',
    price: '27',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '6',
    typeId: '3',
  },
  {
    id: '6',
    address: 'Calle de la Rosa',
    zip: '28',
    sender: 'María García',
    recipient: 'Juan López',
    weight: '3.2',
    price: '32',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '1',
    typeId: '3',
  },
  {
    id: '7',
    address: 'Carrera del Norte',
    zip: '29',
    sender: 'Sofía Martín',
    recipient: 'Javier Soto',
    weight: '0.4',
    price: '4',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '1',
    typeId: '3',
  },
  {
    id: '8',
    address: 'Avenida de la Luna',
    zip: '17',
    sender: 'Pedro Sanchéz',
    recipient: 'Luisa González',
    weight: '3.2',
    price: '32',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '2',
    typeId: '3',
  },
  {
    id: '9',
    address: 'Avenida de las Flores',
    zip: '12',
    sender: 'José Rodríguez',
    recipient: 'María López',
    weight: '1',
    price: '10',
    createdAt: '2023-10-20 15:53:49',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '1',
    typeId: '3',
  },
  {
    id: '10',
    address: 'Avenida del Bosque',
    zip: '22',
    sender: 'Hector Granell',
    recipient: 'Antonio Martínez',
    weight: '123',
    price: '1100.5',
    createdAt: '2023-10-21 15:56:54',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '3',
    typeId: '5',
  },
  {
    id: '11',
    address: 'Calle Montaña',
    zip: '46',
    sender: 'Luis Argente',
    recipient: 'Carlos Torres',
    weight: '2.122',
    price: '21.22',
    createdAt: '2023-10-21 15:57:53',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '1',
    typeId: '3',
  },
  {
    id: '12',
    address: 'Paseo de las Estrellas',
    zip: '18',
    sender: 'Núria Ferrer',
    recipient: 'Carla Ferrer',
    weight: '15',
    price: '182.5',
    createdAt: '2023-10-21 15:58:27',
    updatedAt: '2023-10-21 18:00:54',
    companyId: '2',
    typeId: '5',
  },
  {
    id: '13',
    address: 'Avenida de las Olas',
    zip: '24',
    sender: 'Pablo Ruiz',
    recipient: 'Miguel Roig',
    weight: '231',
    price: '2018.5',
    createdAt: '2023-10-22 18:02:36',
    updatedAt: '2023-10-22 18:02:36',
    companyId: '5',
    typeId: '5',
  },
  {
    id: '14',
    address: 'Calle Albalat',
    zip: '32',
    sender: 'Hector Granell',
    recipient: 'Alejandro Moreno',
    weight: '0.1',
    price: '0.5',
    createdAt: '2023-10-22 18:03:39',
    updatedAt: '2023-10-22 18:03:39',
    companyId: '3',
    typeId: '1',
  },
  {
    address: 'Avenida de las Flores',
    zip: '12',
    sender: 'José Maria Rodríguez',
    recipient: 'María López',
    weight: '1',
    price: '10',
    companyId: '1',
    typeId: '3',
  },
  {
    address: 'Avenida del Bosque',
    zip: '22',
    sender: 'Antonio Martínez',
    recipient: 'Hector Granell',
    weight: '123',
    price: '1100.5',
    companyId: '3',
    typeId: '5',
  },
];
